server.port: 9090
spring:
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/task_manager_db
        username: postgres
        password: fortnite
        driverClassName: org.postgresql.Driver
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/ILV